version: '3'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=channels_sockets.settings
    command: daphne channels_sockets.asgi:application -b 0.0.0.0 -p 8008
    ports:
      - "8008:8008"
    depends_on:
      - redis
